
CREATE TABLE TEACHER
(
ID int IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50)NOT NULL,
) ;
GO
CREATE TABLE STUDENT
(
ID int IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50)NOT NULL,
) ;
GO
CREATE TABLE SUBJECT
(
ID int IDENTITY(1,1) PRIMARY KEY,
TITLE VARCHAR(50) NOT NULL,
COURSE INTEGER NOT NULL,
) ;
GO

CREATE TABLE TEACHER_SUBJECT
(
ID_SUBJECT INTEGER NOT NULL REFERENCES SUBJECT(ID)ON DELETE CASCADE,
ID_TEACHER INTEGER NOT NULL REFERENCES TEACHER(ID)ON DELETE CASCADE,
CONSTRAINT TEACHER_SUBJECT_primary_key PRIMARY KEY (ID_SUBJECT,ID_TEACHER)
) ;
GO
CREATE TABLE STUDENT_SUBJECT
(
ID_SUBJECT INTEGER NOT NULL REFERENCES SUBJECT(ID) ON DELETE CASCADE,
ID_STUDENT INTEGER NOT NULL REFERENCES STUDENT(ID) ON DELETE CASCADE,
CONSTRAINT STUDENT_SUBJECT_primary_key PRIMARY KEY (ID_SUBJECT,ID_STUDENT)
) ;

